---
repo-name: peripherals-kinetic-task
categories:
- Automation
- DevOps
display-name: Kinetic Task
manufacture: Kinetic
product: Task
description: The Workflow component of the Kinetic Platform.
thumbnail: thumbnail.png
